web/main/forms/users.py
from flask_wtf import FlaskForm
import wtforms as wtf
from wtforms.fields.html5 import EmailField

class NewUser(FlaskForm):

    email = EmailField(
        label="Email",
        validators=[
            wtf.validators.DataRequired(message="This field is required"),
            wtf.validators.Email(message="Wrong email format")])
    password = wtf.PasswordField(
        label="Password",
        validators=[
            wtf.validators.DataRequired(message="This field is required"),
            wtf.validators.EqualTo("re_password", message="The passwords must match")])
    re_password = wtf.PasswordField(
        label="Repeat password",
        validators=[
            wtf.validators.DataRequired(message="This field is required")
        ])
    admin_choices = [(1, 'True'), (0, 'False')]
    admin = wtf.RadioField(
        label="Administrator",
        validators=[wtf.validators.InputRequired(message="This field is required")],
        choices=admin_choices,
        coerce=int)
    submit_button = wtf.SubmitField(label="Save")


class UserToEdit(FlaskForm):
    email = EmailField(
        label="Email",
        validators=[
            wtf.validators.DataRequired(message="This field is required"),
            wtf.validators.Email(message="Wrong email format")])
    admin_choices = [(1, 'True'), (0, 'False')]
    admin = wtf.RadioField(
        label="Administrator",
        validators=[wtf.validators.InputRequired(message="This field is required")],
        choices=admin_choices,
        coerce=int)
    submit_button = wtf.SubmitField(label="Save")

web/main/routes/main.py
"""
-----------------------------------------------------------------------------
                                  M A I N
-----------------------------------------------------------------------------
"""
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required

from main.routes.auth import admin_required


main = Blueprint('main', __name__, url_prefix='/')


@main.route('/')
def index():
    return redirect(url_for('v_seism.main'))


# Administrator's home
@main.route('/admin/')
@login_required
@admin_required
def admin_index():
    return render_template('derived/admin-home.html')


# Seismologist's home
@main.route('/')
@login_required
def seismologist_index():
    return render_template(url_for('u_seisms.main'))

web/main/routes/users.py
"""
-----------------------------------------------------------------------------
                                  U S E R S
-----------------------------------------------------------------------------
"""

import json
from flask import Blueprint, render_template, current_app, redirect, url_for, flash
from flask_login import login_required

import main.forms as f
from main.routes.auth import admin_required
from main.utilities.api_querying import makeRequest

user_ = Blueprint('user', __name__, url_prefix='/users/')


@user_.route('/')
@login_required
@admin_required
def main():
    url = current_app.config["API_URL"] + "/users"
    query = makeRequest("GET", url, authenticated_user=True)
    users = json.loads(query.text)["users"]
    return render_template('/derived/users/main.html', users=users)


@user_.route('/add/', methods=["POST", "GET"])
@login_required
@admin_required
def add_user():
    url = current_app.config["API_URL"] + "/users"
    form = f.NewUserForm()

    if form.validate_on_submit():
        """
        If form is validated and submitted, we make a POST request to add an user.
        """
        if form.admin.data == 0:
            form.admin.data = False
        else:
            form.admin.data = True
        user = {
            "email": form.email.data,
            "password": form.password.data,
            "admin": form.admin.data
        }
        user_json = json.dumps(user)
        makeRequest("POST", url, authenticated_user=True, data=user_json)

        return redirect(url_for('user.main'))

    return render_template('/derived/users/add-user.html', form=form)


@user_.route('/edit/<int:id>', methods=["POST", "GET"])
@login_required
@admin_required
def edit_user(id):
    form = f.UserToEditForm()
    url = current_app.config["API_URL"] + "/user/" + str(id)
    query = makeRequest("GET", url, authenticated_user=True)
    if not form.is_submitted():
        """
        If form is not submitted, we store the query.text data from the GET request inside the form's parameters.
        """
        if query.status_code == 404:
            flash("User not found", "warning")
            return redirect(url_for('user.main'))

        # Saving the json to a Python dict in order to show it for editing
        user = query.json()
        if not user["admin"]:
            form.admin.data = 0
        else:
            form.admin.data = 1

        form.email.data = user["email"]
        form.admin.data = user["admin"]

    if form.validate_on_submit():
        """
        Once it is validated and submitted, we store the form's parameters data inside the json for the GET request.
        """
        if form.admin.data == 0:
            form.admin.data = False
        else:
            form.admin.data = True
        user = {
            "email": form.email.data,
            "admin": form.admin.data
        }
        user_data = json.dumps(user)

        makeRequest("PUT", url, authenticated_user=True, data=user_data)
        return redirect(url_for('user.main'))

    return render_template('/derived/users/edit-user.html', id=id, form=form, user=query.json())


@user_.route('/delete/<int:id>')
@login_required
@admin_required
def delete_user(id):
    url = current_app.config["API_URL"] + "/user/" + str(id)
    data = makeRequest("DELETE", url, authenticated_user=True)
    if data.status_code == 409:
        flash("User not found", "warning")
        return redirect(url_for('user.main'))
    return redirect(url_for('user.main'))

web/main/templates/derived/users/add-user.html
{% extends 'principal/main.html' %}

{% from '/macros/forms.html' import generateNewUserForm %}

{% block head %} {{ super() }}

<title>New user · Seismology Institute</title>

{% endblock %}

{% block content %}


<div class="container-fluid my-3 px-5">
    <div class="row">
        <div class="col-lg-auto col-sm-auto col-md-auto">
            <nav aria-label="breadcrumb mr-n5">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{url_for('main.admin_index')}}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{url_for('user.main')}}">Users</a></li>
                    <li class="breadcrumb-item active" aria-current="page">New user</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10 col-sm-12">
            <!-- TITLE -->
            <h3 class="py-2">New user</h3>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <div class="col-lg-2">
        </div>
        <div class="col-sm-12 col-lg-8">
            <div class="container py-2 justify-content-center">
                <h5 class="py-3">Complete the following form</h5>
                <form class="needs-validation" method="POST" action="{{ url_for('user.add_user') }}">
                    {{ generateNewUserForm(form) }}
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock%}

web/main/templates/derived/users/edit-user.html
{% extends 'principal/main.html' %}

{% from '/macros/forms.html' import generateEditUserForm %}

{% block head %}

{{ super() }}

<title>User no.{{user.id_num}} · Seismology Institute</title>

{% endblock %}

{% block content %}

<div class="container-fluid my-3 px-5">
    <div class="row">
        <div class="col-lg-auto col-sm-auto col-md-auto">
            <nav aria-label="breadcrumb mr-n5">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{url_for('main.admin_index')}}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{url_for('user.main')}}">Users</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{user.id_num}}</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10 col-sm-12">
            <!-- TITLE -->
            <h3 class="py-2">Editing user</h3>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <div class="col-lg-2">
        </div>
        <div class="col-sm-12 col-lg-8">
            <div class="container py-2 justify-content-center">

                <h5 class="py-3">Complete the following form</h5>
                <form method="POST" action="{{ url_for('user.edit_user', id=id) }}">
                    {{ generateEditUserForm(form) }}
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock%}

web/main/templates/derived/users/main.html
{% extends 'principal/main.html' %}

{% from '/macros/utilities.html' import listUsers %}

{% block head %}

{{ super() }}

<title>Users · Seismology Institute</title>

{% endblock %}

{% block content %}

<!-- BREADCRUM -->
<div class="container-fluid my-3 px-5">
    <div class="row">
        <div class="col-lg-auto col-sm-auto col-md-auto">
            <nav aria-label="breadcrumb mr-n5">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{url_for('main.admin_index')}}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Users</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-2">
        </div>
        <div class="col-md-12 col-lg-8">
            <!-- TITLE -->
            <h3>Users</h3>
            <!-- BUTTONS -->
            <div class="form-inline py-2 pr-3">
                <a class="btn btn-success" href="{{url_for('user.add_user')}}" role="button">New user</a>
            </div>
            <table class="table table-responsive-md table-hover mt-3">
                <thead>
                    <tr>
                        <th scope="col" class="text-center">ID</th>
                        <th scope="col" class="text-center">Administrator</th>
                        <th scope="col" class="text-center">Email</th>
                        <th scope="col" class="text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {{ listUsers(users) }}
                </tbody>
            </table>
        </div>
        <div class="col-lg-2">
        </div>
    </div>
</div>

{% endblock %}