web/main/forms/sensors.py
from flask_wtf import FlaskForm
import wtforms as wtf



class NewSensor(FlaskForm):

    name = wtf.StringField(
        label="Name",
        validators=[wtf.validators.DataRequired(message="This field is required")]
    )
    ip = wtf.StringField(
        label="IP Address",
        validators=[wtf.validators.DataRequired(message="This field is required")]
    )
    port = wtf.IntegerField(
        label="Port",
        validators=[wtf.validators.DataRequired(message="This field is required")]
    )
    status_choices = [(1, 'Working'), (0, 'Not-working')]
    status = wtf.RadioField(
        label="Status",
        choices=status_choices,
        validators=[wtf.validators.InputRequired(message="This field is required")],
        coerce=int
    )
    active_choices = [(1, 'True'), (0, 'False')]
    active = wtf.RadioField(
        label="Active",
        choices=active_choices,
        validators=[wtf.validators.InputRequired(message="This field is required")],
        coerce=int
    )
    user_id = wtf.SelectField(
        label="Associated seismologist",
        validators=[wtf.validators.InputRequired(message="This field is required")],
        coerce=int)
    submit_button = wtf.SubmitField(label="Save")


class SensorsFilterForm(FlaskForm):
    name = wtf.StringField(
        label="Sensor name",
        validators=[wtf.validators.optional()]
    )
    status = wtf.RadioField(
        label="Status",
        choices=[(1, 'Working'), (0, 'Not-working')],
        validators=[wtf.validators.optional()],
        coerce=int
    )
    active = wtf.RadioField(
        label="Active",
        choices=[(1, 'True'), (0, 'False')],
        validators=[wtf.validators.optional()],
        coerce=int
    )
    user_email = wtf.StringField(
        label="User email",
        validators=[wtf.validators.optional()]
    )

    sort_by = wtf.HiddenField()
    elem_per_page = wtf.IntegerField(
        validators=[wtf.validators.optional()]
        )
    submit_button = wtf.SubmitField(label="Apply filters")

web/main/routes/main.py
"""
-----------------------------------------------------------------------------
                                  M A I N
-----------------------------------------------------------------------------
"""
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required

from main.routes.auth import admin_required


main = Blueprint('main', __name__, url_prefix='/')


@main.route('/')
def index():
    return redirect(url_for('v_seism.main'))


# Administrator's home
@main.route('/admin/')
@login_required
@admin_required
def admin_index():
    return render_template('derived/admin-home.html')


# Seismologist's home
@main.route('/')
@login_required
def seismologist_index():
    return render_template(url_for('u_seisms.main'))

web/main/routes/sensors.py
"""
-----------------------------------------------------------------------------
                                S E N S O R S
-----------------------------------------------------------------------------
"""
import json
from flask import Blueprint, render_template, current_app, redirect, url_for, request, flash
from flask_login import login_required

import main.forms as f
from main.utilities.api_querying import makeRequest
from main.routes.auth import admin_required

sensors_ = Blueprint('sensors', __name__, url_prefix='/sensors/')


@sensors_.route('/')
@login_required
@admin_required
def main():
    url = current_app.config["API_URL"] + "/sensors"
    filters = f.SensorsFilterForm(request.args, meta={'csrf': False})

    query = makeRequest("GET", url, authenticated_user=True)
    sensors = json.loads(query.text)["sensors"]

    data = {}

    if 'name' in request.args and request.args['name'] != "":
        data["name"] = request.args.get('name', '')

    if 'status' in request.args and request.args['status'] != "":
        data["status"] = request.args.get('status', '')

    if 'active' in request.args and request.args['active'] != "":
        data["active"] = request.args.get('active', '')

    if 'user_email' in request.args and request.args['user_email'] != "":
        data["user_email"] = request.args.get('user_email', '')

    if 'sort_by' in request.args and request.args['sort_by'] != "":
        data["sort_by"] = request.args.get('sort_by', '')

    if 'page_num' in request.args and request.args['page_num'] != "":
        data["page_num"] = request.args.get('page_num', '')
        
    if 'elem_per_page' in request.args and request.args['elem_per_page'] != "":
        data["elem_per_page"] = request.args.get('elem_per_page', '')


    data = json.dumps(data)
    query = makeRequest("GET", url, authenticated_user=True, data=data)

    if query.status_code == 200:
        sensors = json.loads(query.text)["sensors"]

        pagination = {"items_num": json.loads(query.text)["items_num"],
                      "total_pages": json.loads(query.text)["total_pages"],
                      "page_num": json.loads(query.text)["page_num"]}

        return render_template('/derived/sensors/main.html',
                               sensors=sensors,
                               filters=filters,
                               pagination=pagination)

    else:
        return redirect(url_for('sensors.main'))


@sensors_.route('/add/', methods=["POST", "GET"])
@login_required
@admin_required
def add_sensor():
    url = current_app.config["API_URL"] + "/sensors"
    form = f.NewSensorForm()

    """
    We make a GET request to achieve the user emails and append them to the user_id.choices of the form
    """
    users_url = current_app.config["API_URL"] + "/users"
    u_data = makeRequest("GET", users_url, authenticated_user=True)
    user_json = json.loads(u_data.text)

    email_list = [(0, "Select one seismologist email")]
    for user in user_json["users"]:
        email_list.append((user["id_num"], user["email"]))
    form.user_id.choices = email_list

    if form.validate_on_submit():
        """
        Once it is validated and submitted, we store the form's parameters data inside the json for the POST request.
        """
        if form.status.data == 0:
            form.status.data = False
        else:
            form.status.data = True

        if form.active.data == 0:
            form.active.data = False
        else:
            form.active.data = True

        u_id = form.user_id.data

        sensor = {
            "name": form.name.data,
            "ip": form.ip.data,
            "port": form.port.data,
            "status": form.status.data,
            "active": form.active.data,
            "user_id": u_id
        }
        sensor_json = json.dumps(sensor)

        u_data = makeRequest("POST", url, authenticated_user=True, data=sensor_json)
        return redirect(url_for('sensors.main'))

    return render_template('/derived/sensors/add-sensor.html', form=form)


@sensors_.route('/edit/<int:id>', methods=["POST", "GET"])
@login_required
@admin_required
def edit_sensor(id):
    url = current_app.config["API_URL"] + "/sensor/" + str(id)
    form = f.NewSensorForm()

    """
    We make a GET request to achieve the user emails and append them to the user_id.choices of the form
    """
    users_url = current_app.config["API_URL"] + "/users"
    u_data = makeRequest("GET", users_url, authenticated_user=True)
    user_json = json.loads(u_data.text)
    email_list = [(0, "Select one seismologist email")]
    for user in user_json["users"]:
        email_list.append((int(user["id_num"]), user["email"]))
    form.user_id.choices = email_list

    if not form.is_submitted():
        """
        If form is not submitted, we store the data.json() from the GET request inside the form's parameters.
        """
        data = makeRequest("GET", url, authenticated_user=True)

        if data.status_code == 404:
            flash("Sensor not found", "warning")
            return redirect(url_for('sensors.main'))

        # Saving the json to a Python dict in order to show it for editing
        sensor = data.json()

        form.name.data = sensor["name"]
        form.ip.data = sensor["ip"]
        form.port.data = sensor["port"]
        if sensor["status"] is False:
            form.status.data = 0
        else:
            form.status.data = 1
        if sensor["active"] is False:
            form.active.data = 0
        else:
            form.active.data = 1

        try:
            if sensor["user_id"] in sensor:
                for id_num, _email in email_list:
                    if id_num == int(sensor["user_id"]):
                        form.user_id.data = int(id_num)
        except KeyError:
            pass

        try:
            user_a = sensor["user"]
            for id_num, _email in email_list:
                if id_num == int(user_a["id_num"]):
                    form.user_id.data = int(id_num)
        except KeyError:
            pass

    if form.validate_on_submit():

        if form.status.data == 0:
            form.status.data = False
        else:
            form.status.data = True
        if form.active.data == 0:
            form.active.data = False
        else:
            form.active.data = True

        u_id = form.user_id.data

        sensor = {
            "name": form.name.data,
            "ip": form.ip.data,
            "port": form.port.data,
            "status": form.status.data,
            "active": form.active.data,
            "user_id": u_id
        }
        sensor_data = json.dumps(sensor)
        u_data = makeRequest("PUT", url, authenticated_user=True, data=sensor_data)
        return redirect(url_for('sensors.main'))

    return render_template('/derived/sensors/edit-sensor.html', id=id, form=form)


@sensors_.route('/delete/<int:id>')
@login_required
@admin_required
def delete_sensor(id):
    url = current_app.config["API_URL"] + "/sensor/" + str(id)
    query = makeRequest("DELETE", url, authenticated_user=True)
    if query.status_code == 409:
        flash(query.text.replace('"', ''), "danger")
        return redirect(url_for('sensors.main'))
    else:
        return redirect(url_for('sensors.main'))


@sensors_.route('/view/<int:id>')
@login_required
@admin_required
def view_sensor(id):
    url = current_app.config["API_URL"] + "/sensor/" + str(id)
    query = makeRequest("GET", url, authenticated_user=True)
    if query.status_code == 404:
        flash("Sensor not found", "warning")
        return redirect(url_for('sensors.main'))
    sensor = query.json()
    return render_template('/derived/sensors/view-sensor.html', sensor=sensor)


@sensors_.route('/check/<int:id>')
@login_required
@admin_required
def check_sensor(id):
    url = current_app.config["API_URL"] + "/sensor/check/" + str(id)
    query = makeRequest("GET", url, authenticated_user=True)
    if query.status_code == 409:
        flash(query.text.replace('"', ''), "danger")
        return redirect(url_for('sensors.main'))
    elif query.status_code == 201:
        flash(query.text.replace('"', ''), "success")
        return redirect(url_for('sensors.main'))
    else:
        flash(query.text.replace('"', ''), "success")
        return redirect(url_for('sensors.main'))


@sensors_.route('/email')
@login_required
@admin_required
def send_emails():
    url = current_app.config["API_URL"] + "/sensors/status"
    query = makeRequest("GET", url, authenticated_user=True)
    if query.status_code == 200:
        flash("Email sent to administrators", "success")
    return redirect(url_for('sensors.main'))

web/main/templates/derived/sensors/add-sensor.html
{% extends 'principal/main.html' %}

{% from '/macros/forms.html' import generateNewSensorForm %}

{% block head %} {{ super() }}

<title>New sensor · Seismology Institute</title>

{% endblock %}

{% block content %}

<div class="container-fluid my-3 px-5">
    <div class="row">
        <div class="col-lg-auto col-sm-auto col-md-auto">
            <nav aria-label="breadcrumb mr-n5">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{url_for('main.admin_index')}}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{url_for('sensors.main')}}">Sensors</a></li>
                    <li class="breadcrumb-item active" aria-current="page">New sensor</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10 col-sm-12">
            <!-- TITLE -->
            <h3 class="py-2">New sensor</h3>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <div class="col-lg-2">
        </div>
        <div class="col-sm-12 col-lg-8">
            <div class="container py-2 justify-content-center">
                <h5 class="py-3">Complete the following form</h5>
                <form method="POST" action="{{ url_for('sensors.add_sensor') }}">
                    {{ generateNewSensorForm(form) }}
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock%}

web/main/templates/derived/sensors/edit-sensor.html
{% extends 'principal/main.html' %}

{% from '/macros/forms.html' import generateNewSensorForm %}

{% block head %} 

{{ super() }}

<title>Sensor no.{{ id }} · Seismology Institute</title>

{% endblock %}

{% block content %}

<div class="container-fluid my-3 px-5">
    <div class="row">
        <div class="col-lg-auto col-sm-auto col-md-auto">
            <nav aria-label="breadcrumb mr-n5">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{url_for('main.admin_index')}}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{url_for('sensors.main')}}">Sensors</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ id }}</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10 col-sm-12">
            <!-- TITLE -->
            <h3 class="py-2">Editing sensor</h3>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <div class="col-lg-2">
        </div>
        <div class="col-sm-12 col-lg-8">
            <div class="container py-2 justify-content-center">

                <h5 class="py-3">Complete the following form</h5>
                <form method="POST" action="{{ url_for('sensors.edit_sensor', id=id) }}">
                    {{ generateNewSensorForm(form) }}
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock%}

web/main/templates/derived/sensors/main.html
{% extends 'principal/main.html' %}

{% from '/macros/utilities.html' import listSensors, showSensorsPagination %}
{% from '/macros/forms.html' import SensorsFiltersForm %}

{% block head %}

{{ super() }}

<title>Sensors · Seismology Institute</title>



{% endblock %}


{% block content %}


<div class="container-fluid my-3 px-5">
    <!-- BREADCRUM -->
    <div class="row">
        <div class="col-lg-auto col-sm-auto col-md-auto">
            <nav aria-label="breadcrumb mr-n5">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{url_for('main.admin_index')}}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Sensors</li>
                </ol>
            </nav>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12 col-lg-2">
        </div>

        <div class="col-md-12 col-lg-8">
            <div class="container py-2">
                <!-- TITLE -->
                <h3>Sensors</h3>

                <!-- FILTERS -->
                {{ SensorsFiltersForm(filters) }}

                <!-- TABLE -->
                {{ listSensors(sensors) }}
                
                {% if sensors|length > 0 %}
                    <!-- PAGINATION -->
                    {{ showSensorsPagination(pagination) }}
                {% endif %}
            </div>
        </div>

        <div class="col-md-12 col-lg-2">
        </div>
    </div>
</div>
{% endblock %}

web/main/templates/derived/sensors/view-sensor.html
{% extends 'principal/main.html' %}

{% block head %} {{ super() }}

<title>Sensor no.{{ sensor.id_num }} · Seismology Institute</title>

{% endblock %}

{% block content %}

<div class="container-fluid my-3 px-5">
    <div class="row">
        <div class="col-lg-auto col-sm-auto col-md-auto">
            <nav aria-label="breadcrumb mr-n5">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{url_for('main.admin_index')}}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{url_for('sensors.main')}}">Sensors</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ sensor.id_num }}</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10 col-sm-12">
            <!-- TITLE -->
            <h3 class="py-2">Sensor</h3>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <div class="col-lg-2">
        </div>
        <div class="col-sm-12 col-lg-8">
            <div class="container py-2 justify-content-center">
                <table class="table table-hover py-3 mb-5">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Status</th>
                            <th scope="col">IP</th>
                            <th scope="col">Port</th>
                            <th scope="col">Active</th>
                            <th scope="col">Associated seismologist</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ sensor.name }}</td>
                            <td>{{ sensor.status }}</td>
                            <td>{{ sensor.ip }}</td>
                            <td>{{ sensor.port }}</td>
                            <td>{{ sensor.active }}</td>
                            {% if sensor.user %}
                            <td>{{ sensor.user.email }}</td>
                            {% else %}
                            <td>Not assigned</td>
                            {% endif %}
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="form-inline justify-content-center">

                <a name="" id="" class="btn btn-dark mx-5" href="{{url_for('sensors.edit_sensor', id=sensor.id_num)}}"
                    role="button">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path
                            d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                        <path fill-rule="evenodd"
                            d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                    </svg>
                    Edit
                </a>
                <a name="" id="" class="btn btn-danger mx-5 my-5"
                    href="{{url_for('sensors.delete_sensor', id=sensor.id_num)}}" role="button" data-toggle="modal"
                    data-target="#deleteModal">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path
                            d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                        <path fill-rule="evenodd"
                            d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                    </svg>
                    Delete
                </a>

                <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel"><strong>Warning</strong></h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                You are deleting sensor "{{ sensor.name }}". Do you want to continue?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Go back</button>
                                <a class="btn btn-danger" href="{{url_for('sensors.delete_sensor', id=sensor.id_num)}}"
                                    role="button">Delete sensor</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock%}