web/main/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, current_app, request, make_response, flash
from flask_login import login_user, logout_user, current_user
from functools import wraps
import requests
import json

from main.forms import LoginForm
from main.utilities import LoggedUser


auth = Blueprint('auth', __name__, url_prefix='/')


@auth.route('/login', methods=["POST","GET"])
def login():
    url = current_app.config['API_URL'] + '/auth/login'
    login_form = LoginForm()

    if login_form.validate_on_submit():
        data = {
            "email": login_form.email.data,
            "password": login_form.password.data
        }
        r = requests.post(url=url, headers={'content-type': 'application/json'}, data=json.dumps(data))

        if r.status_code == 200:
            user_json = json.loads(r.text)
            logged_user = LoggedUser(
                id=user_json['id_num'],
                email=user_json['email'],
                admin=user_json['admin']
            )
            login_user(logged_user)  # Logs in the user
            if user_json['admin'] == True:
                req = make_response(redirect(url_for('main.admin_index')))  # Redirection request
                req.set_cookie('access_token', user_json['token'], httponly=True)
                return req
            if user_json['admin'] == False:
                req = make_response(redirect(url_for('main.seismologist_index')))  # Redirection request
                req.set_cookie('access_token', user_json['token'], httponly=True)
                return req
        else:
            flash("Unknown credentials. Please try again.", 'danger')
            
    return render_template('/derived/log-in.html', login_form=login_form)


@auth.route('/logout')
def logout():
    req = make_response(redirect(url_for('main.index')))  # Redirection request
    req.set_cookie('access_token', '', httponly=True)  # Empty cookie and set expiration date in past
    logout_user()
    return req

def admin_required(fn):
    @wraps(fn)
    def wrapper(*args, **kws):
        if not current_user.admin:
            flash('You are not authorized to enter to this site.', 'warning')
            return redirect(url_for('user.seismologist_index'))
        return fn(*args, **kws)
    return wrapper

web/main/routes/main.py
"""
-----------------------------------------------------------------------------
                                  M A I N
-----------------------------------------------------------------------------
"""
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required

from main.routes.auth import admin_required


main = Blueprint('main', __name__, url_prefix='/')


@main.route('/')
def index():
    return redirect(url_for('v_seism.main'))


# Administrator's home
@main.route('/admin/')
@login_required
@admin_required
def admin_index():
    return render_template('derived/admin-home.html')


# Seismologist's home
@main.route('/')
@login_required
def seismologist_index():
    return render_template(url_for('u_seisms.main'))

web/main/routes/sensors.py
"""
-----------------------------------------------------------------------------
                                S E N S O R S
-----------------------------------------------------------------------------
"""
import json
from flask import Blueprint, render_template, current_app, redirect, url_for, request, flash
from flask_login import login_required

import main.forms as f
from main.utilities.api_querying import makeRequest
from main.routes.auth import admin_required

sensors_ = Blueprint('sensors', __name__, url_prefix='/sensors/')


@sensors_.route('/')
@login_required
@admin_required
def main():
    url = current_app.config["API_URL"] + "/sensors"
    filters = f.SensorsFilterForm(request.args, meta={'csrf': False})

    query = makeRequest("GET", url, authenticated_user=True)
    sensors = json.loads(query.text)["sensors"]

    data = {}

    if 'name' in request.args and request.args['name'] != "":
        data["name"] = request.args.get('name', '')

    if 'status' in request.args and request.args['status'] != "":
        data["status"] = request.args.get('status', '')

    if 'active' in request.args and request.args['active'] != "":
        data["active"] = request.args.get('active', '')

    if 'user_email' in request.args and request.args['user_email'] != "":
        data["user_email"] = request.args.get('user_email', '')

    if 'sort_by' in request.args and request.args['sort_by'] != "":
        data["sort_by"] = request.args.get('sort_by', '')

    if 'page_num' in request.args and request.args['page_num'] != "":
        data["page_num"] = request.args.get('page_num', '')
        
    if 'elem_per_page' in request.args and request.args['elem_per_page'] != "":
        data["elem_per_page"] = request.args.get('elem_per_page', '')


    data = json.dumps(data)
    query = makeRequest("GET", url, authenticated_user=True, data=data)

    if query.status_code == 200:
        sensors = json.loads(query.text)["sensors"]

        pagination = {"items_num": json.loads(query.text)["items_num"],
                      "total_pages": json.loads(query.text)["total_pages"],
                      "page_num": json.loads(query.text)["page_num"]}

        return render_template('/derived/sensors/main.html',
                               sensors=sensors,
                               filters=filters,
                               pagination=pagination)

    else:
        return redirect(url_for('sensors.main'))


@sensors_.route('/add/', methods=["POST", "GET"])
@login_required
@admin_required
def add_sensor():
    url = current_app.config["API_URL"] + "/sensors"
    form = f.NewSensorForm()

    """
    We make a GET request to achieve the user emails and append them to the user_id.choices of the form
    """
    users_url = current_app.config["API_URL"] + "/users"
    u_data = makeRequest("GET", users_url, authenticated_user=True)
    user_json = json.loads(u_data.text)

    email_list = [(0, "Select one seismologist email")]
    for user in user_json["users"]:
        email_list.append((user["id_num"], user["email"]))
    form.user_id.choices = email_list

    if form.validate_on_submit():
        """
        Once it is validated and submitted, we store the form's parameters data inside the json for the POST request.
        """
        if form.status.data == 0:
            form.status.data = False
        else:
            form.status.data = True

        if form.active.data == 0:
            form.active.data = False
        else:
            form.active.data = True

        u_id = form.user_id.data

        sensor = {
            "name": form.name.data,
            "ip": form.ip.data,
            "port": form.port.data,
            "status": form.status.data,
            "active": form.active.data,
            "user_id": u_id
        }
        sensor_json = json.dumps(sensor)

        u_data = makeRequest("POST", url, authenticated_user=True, data=sensor_json)
        return redirect(url_for('sensors.main'))

    return render_template('/derived/sensors/add-sensor.html', form=form)


@sensors_.route('/edit/<int:id>', methods=["POST", "GET"])
@login_required
@admin_required
def edit_sensor(id):
    url = current_app.config["API_URL"] + "/sensor/" + str(id)
    form = f.NewSensorForm()

    """
    We make a GET request to achieve the user emails and append them to the user_id.choices of the form
    """
    users_url = current_app.config["API_URL"] + "/users"
    u_data = makeRequest("GET", users_url, authenticated_user=True)
    user_json = json.loads(u_data.text)
    email_list = [(0, "Select one seismologist email")]
    for user in user_json["users"]:
        email_list.append((int(user["id_num"]), user["email"]))
    form.user_id.choices = email_list

    if not form.is_submitted():
        """
        If form is not submitted, we store the data.json() from the GET request inside the form's parameters.
        """
        data = makeRequest("GET", url, authenticated_user=True)

        if data.status_code == 404:
            flash("Sensor not found", "warning")
            return redirect(url_for('sensors.main'))

        # Saving the json to a Python dict in order to show it for editing
        sensor = data.json()

        form.name.data = sensor["name"]
        form.ip.data = sensor["ip"]
        form.port.data = sensor["port"]
        if sensor["status"] is False:
            form.status.data = 0
        else:
            form.status.data = 1
        if sensor["active"] is False:
            form.active.data = 0
        else:
            form.active.data = 1

        try:
            if sensor["user_id"] in sensor:
                for id_num, _email in email_list:
                    if id_num == int(sensor["user_id"]):
                        form.user_id.data = int(id_num)
        except KeyError:
            pass

        try:
            user_a = sensor["user"]
            for id_num, _email in email_list:
                if id_num == int(user_a["id_num"]):
                    form.user_id.data = int(id_num)
        except KeyError:
            pass

    if form.validate_on_submit():

        if form.status.data == 0:
            form.status.data = False
        else:
            form.status.data = True
        if form.active.data == 0:
            form.active.data = False
        else:
            form.active.data = True

        u_id = form.user_id.data

        sensor = {
            "name": form.name.data,
            "ip": form.ip.data,
            "port": form.port.data,
            "status": form.status.data,
            "active": form.active.data,
            "user_id": u_id
        }
        sensor_data = json.dumps(sensor)
        u_data = makeRequest("PUT", url, authenticated_user=True, data=sensor_data)
        return redirect(url_for('sensors.main'))

    return render_template('/derived/sensors/edit-sensor.html', id=id, form=form)


@sensors_.route('/delete/<int:id>')
@login_required
@admin_required
def delete_sensor(id):
    url = current_app.config["API_URL"] + "/sensor/" + str(id)
    query = makeRequest("DELETE", url, authenticated_user=True)
    if query.status_code == 409:
        flash(query.text.replace('"', ''), "danger")
        return redirect(url_for('sensors.main'))
    else:
        return redirect(url_for('sensors.main'))


@sensors_.route('/view/<int:id>')
@login_required
@admin_required
def view_sensor(id):
    url = current_app.config["API_URL"] + "/sensor/" + str(id)
    query = makeRequest("GET", url, authenticated_user=True)
    if query.status_code == 404:
        flash("Sensor not found", "warning")
        return redirect(url_for('sensors.main'))
    sensor = query.json()
    return render_template('/derived/sensors/view-sensor.html', sensor=sensor)


@sensors_.route('/check/<int:id>')
@login_required
@admin_required
def check_sensor(id):
    url = current_app.config["API_URL"] + "/sensor/check/" + str(id)
    query = makeRequest("GET", url, authenticated_user=True)
    if query.status_code == 409:
        flash(query.text.replace('"', ''), "danger")
        return redirect(url_for('sensors.main'))
    elif query.status_code == 201:
        flash(query.text.replace('"', ''), "success")
        return redirect(url_for('sensors.main'))
    else:
        flash(query.text.replace('"', ''), "success")
        return redirect(url_for('sensors.main'))


@sensors_.route('/email')
@login_required
@admin_required
def send_emails():
    url = current_app.config["API_URL"] + "/sensors/status"
    query = makeRequest("GET", url, authenticated_user=True)
    if query.status_code == 200:
        flash("Email sent to administrators", "success")
    return redirect(url_for('sensors.main'))

web/main/routes/users.py
"""
-----------------------------------------------------------------------------
                                  U S E R S
-----------------------------------------------------------------------------
"""

import json
from flask import Blueprint, render_template, current_app, redirect, url_for, flash
from flask_login import login_required

import main.forms as f
from main.routes.auth import admin_required
from main.utilities.api_querying import makeRequest

user_ = Blueprint('user', __name__, url_prefix='/users/')


@user_.route('/')
@login_required
@admin_required
def main():
    url = current_app.config["API_URL"] + "/users"
    query = makeRequest("GET", url, authenticated_user=True)
    users = json.loads(query.text)["users"]
    return render_template('/derived/users/main.html', users=users)


@user_.route('/add/', methods=["POST", "GET"])
@login_required
@admin_required
def add_user():
    url = current_app.config["API_URL"] + "/users"
    form = f.NewUserForm()

    if form.validate_on_submit():
        """
        If form is validated and submitted, we make a POST request to add an user.
        """
        if form.admin.data == 0:
            form.admin.data = False
        else:
            form.admin.data = True
        user = {
            "email": form.email.data,
            "password": form.password.data,
            "admin": form.admin.data
        }
        user_json = json.dumps(user)
        makeRequest("POST", url, authenticated_user=True, data=user_json)

        return redirect(url_for('user.main'))

    return render_template('/derived/users/add-user.html', form=form)


@user_.route('/edit/<int:id>', methods=["POST", "GET"])
@login_required
@admin_required
def edit_user(id):
    form = f.UserToEditForm()
    url = current_app.config["API_URL"] + "/user/" + str(id)
    query = makeRequest("GET", url, authenticated_user=True)
    if not form.is_submitted():
        """
        If form is not submitted, we store the query.text data from the GET request inside the form's parameters.
        """
        if query.status_code == 404:
            flash("User not found", "warning")
            return redirect(url_for('user.main'))

        # Saving the json to a Python dict in order to show it for editing
        user = query.json()
        if not user["admin"]:
            form.admin.data = 0
        else:
            form.admin.data = 1

        form.email.data = user["email"]
        form.admin.data = user["admin"]

    if form.validate_on_submit():
        """
        Once it is validated and submitted, we store the form's parameters data inside the json for the GET request.
        """
        if form.admin.data == 0:
            form.admin.data = False
        else:
            form.admin.data = True
        user = {
            "email": form.email.data,
            "admin": form.admin.data
        }
        user_data = json.dumps(user)

        makeRequest("PUT", url, authenticated_user=True, data=user_data)
        return redirect(url_for('user.main'))

    return render_template('/derived/users/edit-user.html', id=id, form=form, user=query.json())


@user_.route('/delete/<int:id>')
@login_required
@admin_required
def delete_user(id):
    url = current_app.config["API_URL"] + "/user/" + str(id)
    data = makeRequest("DELETE", url, authenticated_user=True)
    if data.status_code == 409:
        flash("User not found", "warning")
        return redirect(url_for('user.main'))
    return redirect(url_for('user.main'))

web/main/templates/principal/dynamic-tables.html
{% macro showFButtons(field, cancel_url) %}
<div class="form-inline justify-content-center">
	{{ field(class="btn btn-outline-success mx-3")|safe }}
	<a name="" id="" class="btn btn-outline-danger mx-3" href="{{ url_for(cancel_url) }}" role="button">Remove
		parameters</a>
</div>
{% endmacro %}

{% macro showVSeismFButtons(submit, cancel_url) %}
<div class="form-inline justify-content-center">
	{{ submit(class="btn btn-outline-success mx-3")|safe }}
	<a name="" id="" class="btn btn-outline-danger mx-3" href="{{ url_for(cancel_url) }}" role="button">Remove
		parameters</a>
</div>
{% endmacro %}

{% macro showFSelectField(field) %}
<div class="form-group row py-1">
	<label for="fselfield">{{ field.label }}</label>
	{{ field(class="custom-select", id="fselfield")|safe }}
</div>
{% endmacro %}

{% macro showFStringField(field) %}
	<div class="form-group row">
		<div class="col-sm-3 col-lg-2 pt-0 col-form-label">
			<label for="fstrfield">{{ field.label }}</label>
		</div>
		<div class="col-sm-9 col-lg-10">
			{{ field(class="form-control", id="fstrfield")|safe }}
		</div>
	</div>
{% endmacro %}

{% macro showFRadioField(field) %}
	<fieldset class="form-group py-1">
		<div class="row">
			<legend class="col-form-label col-sm-3 col-lg-2 pt-0">{{ field.label }}</legend>
			<div class="col-sm-9 col-lg-10">
				{% for subfield in field %}
				<div class="form-check">
					{{ subfield(class="form-check-input")|safe }}
					{{ subfield.label(class="form-check-label")|safe }}
				</div>
				{% endfor %}
				{{ showErrors(field.errors) }}
			</div>
		</div>
	</fieldset>
{% endmacro %}

{% macro showErrors(errors) %}
{% if errors %}
<div class="container pt-2 px-2 pb-n1 text-danger">
	{% for error in errors %}
	<h6>{{ error }}</h6><br>
	{% endfor %}
</div>
{% endif %}
{% endmacro %}

web/main/templates/principal/global-forms.html
{% macro showStringField(field) %}
<div class="form-group row py-1">
	<div class="col-sm-2">{{ field.label }}{% if field.flags.required %} *{% endif %}</div>
	<div class="col-sm-10">
		{{ field(class="form-control")|safe }}
		{{ showErrors(field.errors) }}
	</div>
</div>
{% endmacro %}

{% macro showIntegerField(field) %}
<div class="form-group row py-1">
	<div class="col-sm-2">{{ field.label }} {% if field.flags.required %} *{% endif %}</div>
	<div class="col-sm-10">
		{{ field(class="form-control")|safe }}
		{{ showErrors(field.errors) }}
	</div>
</div>
{% endmacro %}

{% macro showFloatField(field) %}
<div class="form-group row py-1">
	<div class="col-sm-2">{{ field.label }} {% if field.flags.required %} *{% endif %}</div>
	<div class="col-sm-10">
		{{ field(class="form-control")|safe }}
		{{ showErrors(field.errors) }}
	</div>
</div>
{% endmacro %}

{% macro showSelectField(field) %}
<div class="form-group row py-1">
	<div class="col-sm-2">{{ field.label }} {% if field.flags.required %} *{% endif %}</div>
	<div class="col-sm-10">
		{{ field(class="custom-select")|safe }}
		{{ showErrors(field.errors) }}
	</div>
</div>
{% endmacro %}

{% macro showEmailField(field) %}
<div class="form-group row py-1">
	<div class="col-sm-2">{{ field.label }} {% if field.flags.required %} *{% endif %}</div>
	<div class="col-sm-10">
		{{ field(class="form-control")|safe }}
		{{ showErrors(field.errors) }}
	</div>
</div>
{% endmacro %}

{% macro showPasswordField(field) %} {#  <input type="password"> #}
<div class="form-group row py-1">
	<div class="col-sm-2">{{ field.label }} {% if field.flags.required %} *{% endif %}</div>
	<div class="col-sm-10">
		{{ field(class="form-control")|safe }}
		{{ showErrors(field.errors) }}
	</div>
</div>

{% endmacro %}

{% macro showRadioField(field) %}
<fieldset class="form-group py-1">
	<div class="row">
		<legend class="col-form-label col-sm-2 pt-0">{{ field.label }}{% if field.flags.required %} *{% endif %}</legend>
		<div class="col-sm-10">
			{% for subfield in field %}
			<div class="form-check">
				{{ subfield(class="form-check-input")|safe }}
				{{ subfield.label(class="form-check-label")|safe }}
			</div>
			{% endfor %}
			{{ showErrors(field.errors) }}
		</div>
	</div>
</fieldset>
{% endmacro %}

{% macro showButtons(field, cancel_url) %} {#  <input type="submit"> #}
<div class="form-inline justify-content-center mb-5">
	{{ field(class="btn btn-primary mx-3")|safe }}
	<a name="" id="" class="btn btn-danger mx-3" href="{{url_for(cancel_url)}}" role="button">Cancel</a>
</div>
{% endmacro %}


{% macro showErrors(errors) %}
{% if errors %}
<div class="container pt-2 px-2 pb-n1 text-danger">
	{% for error in errors %}
	<h6>{{ error }}</h6><br>
	{% endfor %}
</div>
{% endif %}
{% endmacro %}


{% macro showStaticData(label, value) %}
<div class="form-group row py-1">
	<div class="col-sm-2"><label for="staticData">{{ label }}</label></div>
	<div class="col-sm-10"><input type="text" readonly class="form-control" id="staticData" value="{{ value }}"></div>
</div>
{% endmacro %}


{% macro showLoginForm(form) %}
{{ form.csrf_token }}
<img class="py-2" src="../../../static/svg/only-vector.svg" alt="" width="" height="">
<h1 class="h3 my-4 font-weight-normal" style="color: rgba(0, 0, 0, 0.75)">Please sign in</h1>

<!-- EMAIL FIELD -->
<label for="inputEmail" class="sr-only">{{ form.email.label }}</label>
{{ form.email(type="email", id="inputEmail", class="form-control my-2", placeholder="Email"|safe) }}
{{ showErrors(form.email.errors) }}

<!-- PASSWORD FIELD -->
<label for="inputPassword" class="sr-only">{{ form.password.label }}</label>
{{ form.password(type="password", id="inputPassword", class="form-control my-2 py", placeholder="Password"|safe) }}
{{ showErrors(form.password.errors) }}

<div class="container w-75">
	{{ form.submit_button(
		class="btn btn-lg btn-light btn-block",
		type="submit",
		style="background-color: #ffca85; border-color: rgba(0, 0, 0, 0.25;)"|safe) }}
</div>

{% endmacro %}

web/main/templates/principal/main.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block head %}
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <!-- CSS -->
  <link rel="stylesheet" href="{{url_for('static', filename='css/body.css')}}" />

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <link
    href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"
    rel="stylesheet" />
  {% endblock %}
</head>

<body>
  {% block header %}
  <!-- HEADER -->
  <header class="navbar navbar-light" style="background-color: #dea364">
    <!-- Logo -->
    <div class="container-fluid justify-content-center">
      <a class="navbar-brand" href=" "><img src="{{url_for('static', filename='svg/vertical-logo.svg')}}" class=""
          height="50" /></a>
    </div>

    <!-- Link buttons & Logged admin mail -->
    <div class="navbar-expand-md navbar-collapse">
      <!-- Collapsible button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible menu -->
      <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
        <!--Links-->
        <ul class="navbar-nav mr-auto">
          <!-- To verified seisms -->
          <li class="nav-item mr-3">
            <a class="nav-link" href="{{url_for('v_seism.main')}}">Verified seisms</a>
          </li>

          {% if current_user.is_authenticated %} {% if not current_user.admin
            %}
          <!-- To verified seisms -->
          <li class="nav-item mr-3">
            <a class="nav-link" href="{{url_for('u_seism.main')}}">Unverified seisms</a>
          </li>
          {% endif %} {% if current_user.admin %}
          <!-- To sensors -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle mr-3" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Sensors
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{url_for('sensors.add_sensor')}}">New sensor</a>
              <a class="dropdown-item" href="{{url_for('sensors.main')}}">View all</a>
            </div>
          </li>

          <!-- To users -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle mr-3" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Users
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{url_for('user.add_user')}}">New user</a>
              <a class="dropdown-item" href="{{url_for('user.main')}}">View all</a>
            </div>
          </li>
          {% endif %} {% endif %}
        </ul>

        {% if current_user.is_authenticated %}
        <!-- Admin profile -->
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              {{ current_user.email }}
            </a>
            <div class="dropdown-menu expanded dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{url_for('auth.logout')}}">Log out</a>
            </div>
          </li>
        </ul>
        {% else %}
        <!-- User's profile -->
        <form class="form-inline">
          <div class="form-group">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link lheading px-5" href="{{url_for('auth.login')}}">Sign in</a>
              </li>
            </ul>
          </div>
        </form>
        {% endif %}
      </div>
    </div>
  </header>

  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}

  <div class="toast fade show" style="position: absolute; top: 130px; right: 20px;">
    <div class="toast-header">
      <strong class="mr-auto">Seismology Institute</strong>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast">&times;</button>
    </div>
    <div class="toast-body text-{{ category }}">{{ message }}</div>
  </div>

  {% endfor %}
  {% endif %}
  {% endwith %}

  {% endblock %}


  {% block content %}
  {% endblock %}

  {% block footer%}

  <footer>
    <div class="d-flex flex-column mt-5 pt-5">
      <nav class="navbar navbar-light" style="background-color: #ffca85;">
        <div class="container-fluid justify-content-center">
          <div class="row">
            {% if current_user.is_authenticated %}
            {% if current_user.admin %}
            <div class="row">
              <!-- To verified seisms -->
              <div class="col-sm-4">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link lheading pr-5" href="{{url_for('v_seism.main')}}">Verified seisms</a>
                  </li>
                </ul>
              </div>
              <!-- To sensors -->
              <div class="col-sm-4">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link lheading pr-5" href="{{url_for('sensors.main')}}">Sensors</a>
                    <a class="nav-link lsubheading pr-5" href="{{url_for('sensors.add_sensor')}}">Add sensor</a>
                  </li>
                </ul>
              </div>
              <!-- To users -->
              <div class="col-sm-4">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link lheading pr-5" href="{{url_for('user.main')}}">Users</a>
                    <a class="nav-link lsubheading pr-5" href="{{url_for('user.add_user')}}">Add user</a>
                  </li>
                </ul>
              </div>
            </div>
            {% else %}
            <div class="row">
              <!-- To verified seisms -->
              <div class="col-sm-6">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link lheading pr-5" href="{{url_for('v_seism.main')}}">Verified seisms</a>
                  </li>
                </ul>
              </div>
              <!-- To unverified seisms -->
              <div class="col-sm-6">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link lheading pr-5" href="{{url_for('u_seism.main')}}">Unverified seisms</a>
                  </li>
                </ul>
              </div>
            </div>
            {% endif %}
            {% else %}
            <div class="row">
              <!-- To verified seisms -->
              <div class="col-sm-3">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link lheading pr-5" href="{{url_for('v_seism.main')}}">Verified seisms</a>
                  </li>
                </ul>
              </div>
            </div>
            {% endif %}
          </div>
        </div>
      </nav>
    </div>
  </footer>

  <!-- JS, Popper.js, and jQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
    integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>

  <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>
  <script>
    $('.toast').toast()
  </script>

  {% endblock %}
</body>

</html>