web/main/routes/main.py
"""
-----------------------------------------------------------------------------
                                  M A I N
-----------------------------------------------------------------------------
"""
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required

from main.routes.auth import admin_required


main = Blueprint('main', __name__, url_prefix='/')


@main.route('/')
def index():
    return redirect(url_for('v_seism.main'))


# Administrator's home
@main.route('/admin/')
@login_required
@admin_required
def admin_index():
    return render_template('derived/admin-home.html')


# Seismologist's home
@main.route('/')
@login_required
def seismologist_index():
    return render_template(url_for('u_seisms.main'))

web/main/routes/unverified_seisms.py
"""
-----------------------------------------------------------------------------
                    U N V E R I F I E D   S E I S M S
-----------------------------------------------------------------------------
"""

import json
import datetime

from flask import Blueprint, render_template, current_app, redirect, url_for, request, flash
from flask_login import login_required

import main.forms as f
from main.utilities.api_querying import makeRequest

u_seism = Blueprint('u_seism', __name__, url_prefix='/unverified-seisms/')


@u_seism.route('/')
@login_required
def main():
    url = current_app.config["API_URL"] + "/unverified-seisms"
    sensors_url = current_app.config["API_URL"] + "/sensors"

    filters = f.USeismsFilterForm(request.args, meta={'csrf': False})

    query = makeRequest("GET", sensors_url, authenticated_user=True)
    sensors = json.loads(query.text)["sensors"]

    filters.sensor_id.choices = [(int(sensor['id_num']), sensor['name']) for sensor in sensors]
    filters.sensor_id.choices.insert(0, [0, "-"])

    data = {}
            
    if 'sensor_id' in request.args:
        data["sensor_id"] = request.args.get('sensor_id', '')        
            
    if "from_datetime" in request.args and request.args["from_datetime"] != "":
        date = datetime.datetime.strptime(request.args.get("from_datetime", ""), "%Y-%m-%dT%H:%M")
        data["from_date"] = datetime.datetime.strftime(date, "%Y-%m-%d %H:%M:%S")

    if "to_datetime" in request.args and request.args["to_datetime"] != "":
        date = datetime.datetime.strptime(request.args.get("to_datetime", ""), "%Y-%m-%dT%H:%M")
        data["to_date"] = datetime.datetime.strftime(date, "%Y-%m-%d %H:%M:%S")

    if 'sort_by' in request.args and request.args['sort_by'] != "":
        data["sort_by"] = request.args.get('sort_by', '')

    if 'page_num' in request.args and request.args['page_num'] != "":
        data["page_num"] = request.args.get('page_num', '')

    if 'elem_per_page' in request.args and request.args['elem_per_page'] != "":
        data["elem_per_page"] = request.args.get('elem_per_page', '')

    data = json.dumps(data)
    query = makeRequest("GET", url, authenticated_user=True, data=data)

    if query.status_code == 200:

        unverified_seisms = json.loads(query.text)["unverified_seisms"]

        pagination = {"items_num": json.loads(query.text)["items_num"],
                      "total_pages": json.loads(query.text)["total_pages"],
                      "page_num": json.loads(query.text)["page_num"]}

        return render_template('/derived/unverified-seisms/main.html',
                               unverified_seisms=unverified_seisms,
                               filters=filters,
                               pagination=pagination)
    else:
        return redirect(url_for('u_seism.main'))


@u_seism.route('/edit/<int:id>', methods=["POST", "GET"])
@login_required
def edit_useism(id):
    url = current_app.config["API_URL"] + "/unverified-seism/" + str(id)
    form = f.SeismForm()

    query = makeRequest("GET", url, authenticated_user=True)
    unverified_seism = query.json()

    if not form.is_submitted():

        # If the form is not sent, makes a request
        if query.status_code == 404:
            flash("Seism not found", "warning")
            return redirect(url_for('u_seism.main'))

        form.depth.data = unverified_seism["depth"]
        form.magnitude.data = unverified_seism["magnitude"]

    if form.validate_on_submit():
        seism = {
            "depth": form.depth.data,
            "magnitude": form.magnitude.data
        }
        seism_json = json.dumps(seism)

        query = makeRequest("PUT", url, authenticated_user=True, data=seism_json)
        return redirect(url_for('u_seism.main'))

    return render_template('/derived/unverified-seisms/edit-useism.html', id=id, form=form,
                           unverified_seism=unverified_seism)


@u_seism.route('/delete/<int:id>')
@login_required
def delete_useism(id):
    url = current_app.config["API_URL"] + "/unverified-seism/" + str(id)
    query = makeRequest("DELETE", url, authenticated_user=True)
    if query.status_code == 409:
        flash("Seism not found", "warning")
        return redirect(url_for('u_seism.main'))
    return redirect(url_for('u_seism.main'))


@u_seism.route('/view/<int:id>')
@login_required
def view_useism(id):
    url = current_app.config["API_URL"] + "/unverified-seism/" + str(id)
    query = makeRequest("GET", url, authenticated_user=True)
    if query.status_code == 404:
        flash("Seism not found", "warning")
        return redirect(url_for('u_seism.main'))
    unverified_seism = query.json()
    return render_template('/derived/unverified-seisms/view-useism.html', unverified_seism=unverified_seism)


@u_seism.route('/validate/<int:id>')
@login_required
def verify_useism(id):
    url = current_app.config["API_URL"] + "/unverified-seism/" + str(id)
    query = makeRequest("GET", url, authenticated_user=True)
    if query.status_code == 404:
        flash("Seism not found", "warning")
        return redirect(url_for('u_seism.main'))

    verification = {
        "verified": True
    }
    data_json = json.dumps(verification)
    _query = makeRequest("PUT", url, authenticated_user=True, data=data_json)

    return redirect(url_for('u_seism.main'))

web/main/templates/derived/unverified-seisms/edit-useism.html
{% extends 'principal/main.html' %} 

{% from '/macros/forms.html' import generateEditSeismForm %}

{% block head %} {{ super() }}

<title>Unverified seism no.{{ unverified_seism.id_num }} · Seismology Institute</title>

{% endblock %}


{% block content %}

<div class="container-fluid my-3 px-5">
    <div class="row">
        <div class="col-lg-auto col-sm-auto col-md-auto">
            <nav aria-label="breadcrumb mr-n5">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{url_for('main.seismologist_index')}}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{url_for('u_seism.main')}}">Unverified seisms</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        {{ unverified_seism.id_num }}
                    </li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10 col-sm-12">
            <!-- TITLE -->
            <h3 class="py-2">Editing unverified seism</h3>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <div class="col-lg-2">
        </div>
        <div class="col-sm-12 col-lg-8">
            <div class="container py-2 justify-content-center">

                <h5 class="py-3">Complete the following form</h5>
                <form method="POST" action="{{ url_for('u_seism.edit_useism', id=id) }}">
                    {{ generateEditSeismForm(form, unverified_seism) }}
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock%}

web/main/templates/derived/unverified-seisms/main.html
{% extends 'principal/main.html' %}

{% from '/macros/utilities.html' import listUSeisms, showUSeismsPagination %}
{% from '/macros/forms.html' import USeismsFiltersForm %}

{% block head %}

{{ super() }}


<title>Unverified Seisms · Seismology Institute</title>

{% endblock %}

{% block content %}

<!-- BREADCRUM -->
<div class="container-fluid my-3 px-5">
    <div class="row">
        <div class="col-lg-auto col-sm-auto col-md-auto">
            <nav aria-label="breadcrumb mr-n5">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{url_for('main.seismologist_index')}}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Unverified seisms</li>
                </ol>
            </nav>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12 col-lg-2">
        </div>

        <div class="col-md-12 col-lg-8">
            <div class="container py-2">
                <!-- TITLE -->
                <h3>Unverified seisms</h3>

                <!-- FILTERS -->
                {{ USeismsFiltersForm(filters) }}

                <!-- DINAMIC TABLE -->
                {{ listUSeisms(unverified_seisms) }}

                {% if unverified_seisms|length > 0 %}
                    <!-- TABLE PAGINATION -->
                    {{ showUSeismsPagination(pagination) }}
                {% endif %}
            </div>
        </div>

        <div class="col-md-12 col-lg-2">
        </div>
    </div>
</div>
{% endblock %}

web/main/templates/derived/unverified-seisms/view-useism.html
{% extends 'principal/main.html' %} 
{% from 'macros/utilities.html' import showUSeismMap %} 

{% block head %} 

{{ super() }}

<title>Unverified seism no.{{ unverified_seism.id_num }} · Seismology Institute</title>

{% endblock %}

{% block content %}


<div class="container-fluid my-3 px-5">
    <div class="row">
        <div class="col-lg-auto col-sm-auto col-md-auto">
            <nav aria-label="breadcrumb mr-n5">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{url_for('main.seismologist_index')}}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{url_for('u_seism.main')}}">Unverified seisms</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ unverified_seism.id_num }}</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10 col-sm-12">
            <!-- TITLE -->
            <h3 class="py-2">Unverified seism</h3>
        </div>
        <div class="col-lg-1"></div>
    </div>
</div>

<div class="container my-3 px-5">
    <div class="row">
        <div class="col-sm-12 col-lg-6">
            <div class="container py-2">
                <h5 class="pb-3">Seism's Table</h5>
                <table class="table table-hover py-3">
                    <tbody>
                        <tr>
                            <th scope="row">Date and time</th>
                            <td class="text-center">{{ unverified_seism.datetime }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Depth</th>
                            <td class="text-center">{{ unverified_seism.depth }} mts</td>
                        </tr>
                        <tr>
                            <th scope="row">Magnitude</th>
                            <td class="text-center">{{ unverified_seism.magnitude }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Associated sensor</th>
                            <td class="text-center">{{ unverified_seism.sensor.name }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Longitude</th>
                            <td class="text-center">{{ unverified_seism.longitude }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Latitude</th>
                            <td class="text-center">{{ unverified_seism.latitude }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-sm-12 col-lg-6">
            <div class="container py-2">
                <h5 class="pb-3">Satelital view</h5>
                {{ showUSeismMap(unverified_seism) }}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3">
        </div>
        <div class="col-lg-6 col-md-12 d-flex justify-content-center">
            <div class="btn-toolbar py-2">
                <a name="" id="" class="btn btn-success mx-3" href="{{url_for('u_seism.verify_useism', id=unverified_seism.id_num)}}" role="button">Mark as verified</a>
                <a name="" id="" class="btn btn-dark mx-3" href="{{url_for('u_seism.edit_useism', id=unverified_seism.id_num)}}" role="button">Edit</a>
                <a name="" id="" class="btn btn-danger mx-3" href="{{url_for('u_seism.delete_useism', id=unverified_seism.id_num)}}" role="button">Delete</a>
            </div>
        </div>
        <div class="col-lg-3">
        </div>
    </div>
</div>

{% endblock%}